version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 8600:8080
  frontend:
    build: ./frontend
    ports:
      - 8080:80
    depends_on:
      - backend
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  
